name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USER_APP_NAME: ${{ secrets.USER_APP_NAME }}
      USER_APP_ID: ${{ secrets.USER_APP_ID }}
      USER_APP_KEY: ${{ secrets.USER_APP_KEY }}
      USER_APP_LICENSE: ${{ secrets.USER_APP_LICENSE }}
      USER_DEVELOPER_ACCOUNT: ${{ secrets.USER_DEVELOPER_ACCOUNT }}
      USER_BAUD_RATE: ${{ secrets.USER_BAUD_RATE }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt-get update
          
          # Install required system packages
          sudo apt-get install -y automake libaio-dev libusb-1.0-0-dev unzip cmake build-essential pkg-config
          
          # Install OPUS
          tar -xzvf opus-1.3.1.tar.gz
          cd opus-1.3.1/
          autoreconf -f -i
          ./configure
          make -j4
          sudo make install
          cd ..
          
          # Install FFMPEG
          tar -zxvf ffmpeg-4.3.2.tar.gz
          cd ffmpeg-4.3.2/
          ./configure --enable-shared
          make -j4
          sudo make install
          cd ..
          
          # Install OpenCV
          unzip opencv-3.4.15.zip
          cd opencv-3.4.15/
          mkdir build && cd build/
          cmake ../
          make -j4
          sudo make install
          cd ../..
          
          # Check OpenCV version
          opencv_version
    - name: Build with CMake
      run: |
         mkdir -p build && cd build
         cmake ../ && make -j4
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dji_sdk_demo_binary
        path: build/bin/dji_sdk_proyectoieg
