name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # env:
    #   USER_APP_NAME: ${{ secrets.USER_APP_NAME }}
    #   USER_APP_ID: ${{ secrets.USER_APP_ID }}
    #   USER_APP_KEY: ${{ secrets.USER_APP_KEY }}
    #   USER_APP_LICENSE: ${{ secrets.USER_APP_LICENSE }}
    #   USER_DEVELOPER_ACCOUNT: ${{ secrets.USER_DEVELOPER_ACCOUNT }}
    #   USER_BAUD_RATE: ${{ secrets.USER_BAUD_RATE }}

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
          sudo apt-get update
          
          # Install required system packages
          sudo apt-get install -y automake libaio-dev libusb-1.0-0-dev unzip cmake build-essential pkg-config libhackrf-dev
          
    - name: Create build directory
      run: mkdir -p build

    - name: Configure with CMake
      run: cmake ../ -DCMAKE_POLICY_VERSION_MINIMUM=3.5
      working-directory: build

    - name: Build
      run: make -j4
      working-directory: build
      
    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: dji_sdk_demo_binary
        path: ./build/bin/dji_sdk_proyectoieg
