name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      USER_APP_NAME: ${{ secrets.USER_APP_NAME }}
      USER_APP_ID: ${{ secrets.USER_APP_ID }}
      USER_APP_KEY: ${{ secrets.USER_APP_KEY }}
      USER_APP_LICENSE: ${{ secrets.USER_APP_LICENSE }}
      USER_DEVELOPER_ACCOUNT: ${{ secrets.USER_DEVELOPER_ACCOUNT }}
      USER_BAUD_RATE: ${{ secrets.USER_BAUD_RATE }}

    steps:
    - uses: actions/checkout@v4
    - name: Configure build with CMake
      run: |
         mkdir -p build && cd build
         cmake ../ && make -j4
